### ISSUE TITLE
Implement failing Product validation tests

### ISSUE THREAD

**Issue by ideasasylum** [podia/sebastian-project#2]
I spec'd out two simple tests in the `/test/models/product_test.rb` but I haven't implemented the functionality. Can you handle that for me?

I'd like the product name and path to be required, and I want to ensure that the path only contains letters, numbers, or dashes (so "this-1-is-an-ok-path" but "this is not")

**Comment by sebasoga** [comment]
@ideasasylum I [opened a PR](https://github.com/podia/sebastian-project/pull/7) adding a couple of simple validations to the `Product` model.

With those changes, the tests now pass. Nevertheless, I was wondering if we should also do things like:
- Validate the uniqueness of the `path`. We probably want to prevent path collisions.
- Add DB level constraints, such as making sure `path` and `name` are not empty and `path` is unique.
